// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdW19M-e6ROkOXrfCrHjHlAkZFfabk15Y',
    appId: '1:339692191873:web:4fdb085a4cf55be91a0d80',
    messagingSenderId: '339692191873',
    projectId: 'fruit-hup-editted',
    authDomain: 'fruit-hup-editted.firebaseapp.com',
    storageBucket: 'fruit-hup-editted.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA62maVyshXiUYkzYtZ1_8RZLKPUYhqQCs',
    appId: '1:339692191873:android:570539ace573fb6d1a0d80',
    messagingSenderId: '339692191873',
    projectId: 'fruit-hup-editted',
    storageBucket: 'fruit-hup-editted.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg-xZFYfReF2a7Up9w7c6ZPAR2gfE0zFg',
    appId: '1:339692191873:ios:4cdab585c081e6791a0d80',
    messagingSenderId: '339692191873',
    projectId: 'fruit-hup-editted',
    storageBucket: 'fruit-hup-editted.firebasestorage.app',
    iosBundleId: 'com.example.fruitHup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg-xZFYfReF2a7Up9w7c6ZPAR2gfE0zFg',
    appId: '1:339692191873:ios:4cdab585c081e6791a0d80',
    messagingSenderId: '339692191873',
    projectId: 'fruit-hup-editted',
    storageBucket: 'fruit-hup-editted.firebasestorage.app',
    iosBundleId: 'com.example.fruitHup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdW19M-e6ROkOXrfCrHjHlAkZFfabk15Y',
    appId: '1:339692191873:web:0e490f5fcb4663151a0d80',
    messagingSenderId: '339692191873',
    projectId: 'fruit-hup-editted',
    authDomain: 'fruit-hup-editted.firebaseapp.com',
    storageBucket: 'fruit-hup-editted.firebasestorage.app',
  );
}
